[builtin] revised kpm build (without susfs)

diff --git a/.github/workflows/build-sukisu-kernel.yml b/.github/workflows/build-sukisu-kernel.yml
--- a/.github/workflows/build-sukisu-kernel.yml
+++ b/.github/workflows/build-sukisu-kernel.yml
@@ -54,8 +54,7 @@ jobs:
               REMOVE_UNUSED_PACKAGES
               ENABLE_SUKISU
               SUKISU_TAG
-              ADD_KPM_CONFIG
-              APPLY_SUCOMPAT_PATCH
+              ENABLE_KPM
               APPLY_SUSFS_PATCH
           )
           
@@ -245,11 +244,6 @@ jobs:
           echo "正在打隐藏应用补丁"
           patch -p1 -F 3 < 69_hide_stuff.patch
 
-      - name: Patching bugs
-        run: |
-          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-          sed -i 's/LSM_HOOK_INIT(task_fix_setuid, ksu_task_fix_setuid)$/LSM_HOOK_INIT(task_fix_setuid, ksu_task_fix_setuid),/' drivers/kernelsu/lsm_hook.c
-
       - name: Add Configuration for SukiSU
         run: |
           cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
@@ -282,6 +276,11 @@ jobs:
             echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
             echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
             echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"
+          
+            if grep -q "CMD_SUSFS_ADD_SUS_MAP" "drivers/kernelsu/core_hook.c" >/dev/null 2>&1 || grep -q "CMD_SUSFS_ADD_SUS_MAP" "drivers/kernelsu/supercalls.c" >/dev/null 2>&1; then
+              echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> "$CONFIG_FILE"
+              echo "[+] Detected SUS_MAP."
+            fi
           fi
           
           if [ ${{ env.DISABLE-LTO }} = true ]; then
@@ -294,49 +293,37 @@ jobs:
             echo "CONFIG_CC_WERROR=n" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
           fi
 
-      - name: Handle sukisu nongki issue
-        if: env.APPLY_SUCOMPAT_PATCH == 'true'
+      - name: KPM Configuration
+        if: env.ENABLE_KPM == 'true'
         run: |
           cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-          SUCOMPATH="drivers/kernelsu/sucompat.h"
-          SUCOMPATC="drivers/kernelsu/sucompat.c"
+          pwd
           
-          cat >> "$SUCOMPATC" <<'EOF'
-          
-          /* ===== Backport wrapper for old kernel ===== */
-          int ksu_handle_devpts(struct inode *inode)
-          {
-              if (!inode)
-                  return 0;
-              return __ksu_handle_devpts(inode);
-          }
-          EXPORT_SYMBOL(ksu_handle_devpts);
-          /* ===== End of backport wrapper ===== */
-          
-          EOF
-              echo "sucompat added"
-          
-          if ! grep -q "extern int __ksu_handle_devpts(" "$SUCOMPATH"; then
-              cat >> "$SUCOMPATH" << 'EOF'
-          
-          /* ===== Added for devpts support (KernelSU) ===== */
-          extern int __ksu_handle_devpts(struct inode *inode);
-          extern int ksu_handle_devpts(struct inode *inode);
-          /* ===== End devpts support ===== */
-          EOF
+          if [[ -d "KernelSU/kernel/kpm" ]]; then
+            if [ -f "include/linux/set_memory.h" ]; then
+              echo "CONFIG_KPM=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
+              curl -L "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch
+              if [[ -f patch ]]; then
+                chmod +x patch
+                echo "Running patch..."
+                ./patch
+                echo "KPM applied successfully!"
+              else
+                echo "ERROR: patch_linux failed to download!"
+                exit 1
+              fi
+            else
+              echo "Need to backport set_memory from 4.19"
+              exit 1
+            fi
           fi
-          
-          grep -n "ksu_handle_devpts" drivers/kernelsu/sucompat.c
-          grep -n "ksu_handle_devpts" drivers/kernelsu/sucompat.h
 
       - name: Check defconfig before build
         run: |
           cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
           CONFIG_FILE="arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}"
           echo "=== Checking defconfig file: $CONFIG_FILE ==="
-          cat "$CONFIG_FILE" | grep -E "(KPM|KALLSYMS|KSU|SUFS)" || true
-          echo "=== Full defconfig content ==="
-          cat "$CONFIG_FILE"   
+          cat "$CONFIG_FILE" | grep -E "(KPM|KALLSYMS|KSU|SUFS)" || true  
 
       - name: Setup ccache
         if: env.ENABLE_CCACHE == 'true'
