[tmp-builtin] debug

diff --git a/.github/workflows/build-sukisu-kernel.yml b/.github/workflows/build-sukisu-kernel.yml
--- a/.github/workflows/build-sukisu-kernel.yml
+++ b/.github/workflows/build-sukisu-kernel.yml
@@ -250,8 +250,10 @@ jobs:
         if: env.ENABLE_MANUAL_HOOK == 'true'
         run: |
           cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+          echo "Check line number"
+          grep -n "static int compat_do_execve" fs/exec.c
           nl -ba $GITHUB_WORKSPACE/patches/manual_hooks.patch | sed -n '1,120p'
-          patch --debug=all -p1 -F 3 < $GITHUB_WORKSPACE/patches/manual_hooks.patch || { echo "Patch failed!"; exit 1; }
+          patch -p1 -F 10 -l < $GITHUB_WORKSPACE/patches/manual_hooks.patch || { echo "Patch failed!"; exit 1; }
 
       - name: Add Configuration for SukiSU
         run: |
