[builtin] rebuild

diff --git a/.github/workflows/build-sukisu-kernel.yml b/.github/workflows/build-sukisu-kernel.yml
--- a/.github/workflows/build-sukisu-kernel.yml
+++ b/.github/workflows/build-sukisu-kernel.yml
@@ -245,6 +245,16 @@ jobs:
           echo "正在打隐藏应用补丁"
           patch -p1 -F 3 < 69_hide_stuff.patch
 
+      - name: Patching bugs
+        run: |
+          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+          pwd
+          ls
+          sed -i 's/LSM_HOOK_INIT(task_fix_setuid, ksu_task_fix_setuid)$/LSM_HOOK_INIT(task_fix_setuid, ksu_task_fix_setuid),/' drivers/kernelsu/lsm_hook.c
+          grep -R "LSM_HOOK_INIT(task_fix_setuid, ksu_task_fix_setuid)," -n drivers/kernelsu/lsm_hook.c \
+          && echo "task_fix_setuid patch OK" \
+          || echo "task_fix_setuid patch FAILED"
+
       - name: Add Configuration for SukiSU
         run: |
           cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
